### ISSUE TITLE
Visual indicator on code

### ISSUE THREAD

**Issue by Danieleeee** [patrys/vscode-code-outline#1]
Hi, great extension.
It's possible, after clicking on entity in outline, to have a visual indicator "where given entity is" ?
It may e.g. move cursor to it or highlight this in editor. Also it would be nice to focus editor after clicking.

**Comment by RobertoMalatesta** [comment]
Best plugin ***ever***

-R

**Comment by patrys** [comment]
Done in 0.0.2!

**Comment by Danieleeee** [comment]
Thanks

**Comment by laukikd** [comment]
I have a function declaration in my .h file eg: void Session () inside class ControlNode
On that file Code Outline works great.
I can see Session() in symbol list
In my .cc file i have function definition eg: void ControlNode::Session() {...}
Code Outline doesnot show me that..
I cannot see Session() in symbol list

Is it supposed to work that way or am I using it wrong..
