### ISSUE TITLE
Keep code-outline from constantly re-opening the activity bar

### ISSUE THREAD

**Issue by ricpol** [patrys/vscode-code-outline#107]
Code-outline will *always* show the current node every time I clic on a different line in the editor - at any cost. If its own tab in the activity bar happens to be collapsed at the moment, then code-outline will expand it to show the node. If the activity bar itself is closed, then code-outline will promptly re-open it, bouncing the editors to the left. 
All this zeal is a bit intrusive. If I close my activity bar, I want it to stay closed. There should at least be an option to disable this aggressive behavior.

**Comment by patrys** [comment]
This is caused by VSCode, not the extension. The extension only asks for the currently selected tree node to be changed. See #103

**Comment by ricpol** [comment]
Sorry, I missed #103. 
But still, I'm puzzled... the other tabs in the activity/side bar don't work like this. 
For instance, see the "workspace" tab: if I have multiple open files and I switch between them, the "workspace" tab updates itself, selecting the file currently in foreground. Yet, if the activity bar is closed and/or the workspace tab is collapsed, it doesn't pop out of nowhere just to show me the new selection. Same goes for the "open editors" tab. 
Don't know, maybe it's just the way extensions work. If so, I really think extensions' creators should open a ticket with VSC, because it's really annoying.
