### ISSUE TITLE
unwanted switching from search to explorer sidebar

### ISSUE THREAD

**Issue by gregorleban** [patrys/vscode-code-outline#113]
Hi,

I'm using the extension and I love it. The only annoyance that I'm having with it is the following:

I'm editing some javascript code and open the search sidebar. I enter some function name and find matches. When I click a match, VS Code shows me the code in the editor, but your extension also changes the sidebar from Search to the Explorer. This doesn't happen in all cases and I haven't been able to isolate specifically what determines if it will switch to Explorer or not. It might be if the file clicked in Search is different than the one that was currently open or it might be something else. Could you have a look and fix this?

Thanks and best regards,
Gregor

**Comment by patrys** [comment]
Hey, this was fixed in 0.1.1. See #102, #104
