### ISSUE TITLE
this extension breaks git now

### ISSUE THREAD

**Issue by severak** [patrys/vscode-code-outline#116]
Source control says "There are no source control providers." when this extension is enabled. When I disable it, it works.

System info:

```
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

Extension version: 1.4.0

**Comment by patrys** [comment]
If it says that "there are no _active_ source code providers", click an editor file. It will say that whenever a non-editor pane is focused.

**Comment by severak** [comment]
Aaah. Sorry, I mistaken this extension with https://github.com/oleg-shilo/codemap.vscode
