### ISSUE TITLE
Add code outline as activity bar item instead of panel in explorer item

### ISSUE THREAD

**Issue by PixelT** [patrys/vscode-code-outline#117]
More details about this:
https://code.visualstudio.com/updates/v1_23#_extension-authoring

**Comment by DavidWang88** [comment]
I changed "package.json" of this extension by myself.
![2018-05-06_115813](https://user-images.githubusercontent.com/5523894/39669648-d971008c-5124-11e8-97a3-7f38fcd05bc7.png)

The outline icon on activity bar is here. Cause github doesn't support svg file, so the content of it as follows:
<svg width="50" height="40" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <g>
  <title>Layer 1</title>
  <g stroke="null" id="svg_1">
   <path stroke="null" d="m35.577242,29.788484l-15.882946,0c-0.654613,0 -1.185176,-0.610931 -1.185176,-1.3647s0.530565,-1.3647 1.185176,-1.3647l15.882551,0c0.654613,0 1.185176,0.610931 1.185176,1.3647s-0.530169,1.3647 -1.184781,1.3647l0.000001,0l-0.000001,0l0.000001,0z" id="svg_2"/>
   <path stroke="null" d="m35.577242,21.222266l-15.882946,0c-0.654613,0 -1.185176,-0.610931 -1.185176,-1.3647s0.530565,-1.3647 1.185176,-1.3647l15.882551,0c0.654613,0 1.185176,0.610931 1.185176,1.3647c0.000396,0.753769 -0.530169,1.3647 -1.184781,1.3647l0.000001,0l-0.000001,0l0.000001,0z" id="svg_3"/>
   <path stroke="null" d="m35.577242,12.656049l-15.882946,0c-0.654613,0 -1.185176,-0.610931 -1.185176,-1.3647s0.530565,-1.3647 1.185176,-1.3647l15.882551,0c0.654613,0 1.185176,0.610931 1.185176,1.3647s-0.530169,1.3647 -1.184781,1.3647l0.000001,0l-0.000001,0l0.000001,0z" id="svg_4"/>
   <circle stroke="null" cx="14.601594" cy="11.396887" r="1.366505" id="svg_5"/>
   <circle stroke="null" cx="14.601594" cy="19.857567" r="1.366506" id="svg_6"/>
   <circle stroke="null" cx="14.601594" cy="28.318248" r="1.366505" id="svg_7"/>
  </g>
  <g id="svg_8"/>
  <g id="svg_9"/>
  <g id="svg_10"/>
  <g id="svg_11"/>
  <g id="svg_12"/>
  <g id="svg_13"/>
  <g id="svg_14"/>
  <g id="svg_15"/>
  <g id="svg_16"/>
  <g id="svg_17"/>
  <g id="svg_18"/>
  <g id="svg_19"/>
  <g id="svg_20"/>
  <g id="svg_21"/>
  <g id="svg_22"/>
 </g>
</svg>

**Comment by PixelT** [comment]
https://marketplace.visualstudio.com/items?itemName=252675163.vscode-code-xb1 lol -.-

**Comment by DavidWang88** [comment]
This icon may be better.
[Icon](http://svgur.com/s/6YL)

**Comment by daggilli** [comment]
Having to switch between the Explorer and Outline views renders this extension almost completely unusable. I don;t know what you were even thinking.

**Comment by patrys** [comment]
@daggilli I was thinking that it was the most requested change, it turns out there are other people. Please take your attitude elsewhere.

**Comment by mwfontes** [comment]
@patrys @PixelT Yeah... I totally get the idea... On regular notebook screens it was taking a lot of space and, of course, you do have to make compromises. But in high-res or large screens, it is annoying to have to go back-and-forth, switching between file and outline browsers. I would suggest the ability to choose the layout you prefer (grouped or always open).

Currently, I set a shortcut to open it, but it is not optimal.

It is an awesome extension, btw.

**Comment by patrys** [comment]
@mwfontes Have you tried using the built-in Outline in VSCode Insiders? It's almost identical to my extension and it uses the Explorer pane.

**Comment by mwfontes** [comment]
@patrys Hmmm... nop. I use yours for so long I did not even know that it existed. =) I'll take a look. Cheers!
