### ISSUE TITLE
Feature Request: Work in reverse also?

### ISSUE THREAD

**Issue by smlombardi** [patrys/vscode-code-outline#12]
This is great work.

Would it be possible to also get the reverse: put cursor in code and have the matching item show in the tree?

**Comment by patrys** [comment]
There's currently no VSCode support for affecting tree view selection 😢

**Comment by hex13** [comment]
Something is seriously wrong with VSCode API for custom tree views, if it's so limited.

**Comment by mbahri** [comment]
I think it's still very new so they may add features in future releases :)

**Comment by davecohrs** [comment]
I too hope it will one day be possible to implement this feature. When I'm in the middle of a function, it would be really nice if the name of the function were highlighted in the tree. Something I miss from PyCharm.
