### ISSUE TITLE
After 2.0 update, outline panel disappeared

### ISSUE THREAD

**Issue by ozum** [patrys/vscode-code-outline#120]
Hi,

After upgrading `code-outline` to 2.0, its panel disappeared and several enable/disable uninstall/install cycle, I still cannot see its panel.

MacOS: 10.13.3
VSCode: 1.23.0
Code Outline: 2.0

**Comment by mmtjhlee** [comment]
Can you access it using left-most toolbar?

**Comment by davidesnc** [comment]
open package.json of the extension and change

> "views": {
> 			"outline": [
> 				{
> 					"id": "symbolOutline",

in

> "views": {
> 			"explorer": [
> 				{
> 					"id": "symbolOutline",
> 

this worked for me

**Comment by ozum** [comment]
@davidesnc Thanks.

While trying your suggestion, which works fine, I also realized new button added by `code outline`.

@patrys, for the record, it would be good to add new behaviour to changelog or doc.

![image](https://user-images.githubusercontent.com/1497060/39857805-50e0e478-543d-11e8-8f6e-d5c77f93d955.png)

**Comment by ubo5** [comment]
This is funny. One month ago, I set my activity bar to be not visible. After 2.0 version upgrade, suddenly this behavior become a pain.

**Comment by leanderr** [comment]
@davidesnc Would you be so kind and paste the whole package.json? I cannot get it to work anyhow. Now the Item is gone but still no Outline on the Explorer Pane.. :(

**Comment by davidesnc** [comment]
@leanderr  here it is

{
	"name": "vscode-code-outline",
	"displayName": "Code Outline",
	"description": "A code outline tree provider for VSCode",
	"version": "0.2.0",
	"publisher": "patrys",
	"homepage": "https://github.com/patrys/vscode-code-outline",
	"repository": {
		"type": "git",
		"url": "https://github.com/patrys/vscode-code-outline"
	},
	"icon": "resources/icon.png",
	"galleryBanner": {
		"color": "#292d3e",
		"theme": "dark"
	},
	"engines": {
		"vscode": "^1.23.0"
	},
	"categories": [
		"Other"
	],
	"activationEvents": [
		"onView:symbolOutline"
	],
	"main": "./out/src/extension",
	"contributes": {
		"commands": [
			{
				"command": "symbolOutline.refresh",
				"title": "Refresh code outline",
				"icon": {
					"dark": "resources/dark/icon-refresh.svg",
					"light": "resources/light/icon-refresh.svg"
				}
			},
			{
				"command": "symbolOutline.revealCurrentSymbol",
				"title": "Show in code outline"
			}
		],
		"viewsContainers": {
			"activitybar": [
				{
					"id": "outline",
					"title": "Outline",
					"icon": "resources/icon.svg"
				}
			]
		},
		"views": {
			"explorer": [
				{
					"id": "symbolOutline",
					"name": "Code Outline"
				}
			]
		},
		"menus": {
			"editor/context": [
				{
					"command": "symbolOutline.revealCurrentSymbol",
					"group": "navigation"
				}
			],
			"view/title": [
				{
					"command": "symbolOutline.refresh",
					"when": "view == symbolOutline",
					"group": "navigation"
				}
			]
		},
		"configuration": {
			"type": "object",
			"title": "Code Outline configuration",
			"properties": {
				"symbolOutline.doSort": {
					"type": "boolean",
					"default": false,
					"description": "Sort the outline"
				},
				"symbolOutline.expandNodes": {
					"type": "array",
					"default": [
						"Module",
						"Class",
						"Interface",
						"Namespace",
						"Object",
						"Package",
						"Struct"
					],
					"description": "Kinds of nodes to be expanded automatically."
				},
				"symbolOutline.sortOrder": {
					"type": "array",
					"default": [
						"Class",
						"Module",
						"Constant",
						"Interface",
						"*",
						"Constructor",
						"Function",
						"Method"
					],
					"description": "Order to the sort symbols in, if sorted.  * is placeholder for all symbols not explicitly listed."
				},
				"symbolOutline.topLevel": {
					"type": "array",
					"default": [
						"*"
					],
					"description": "Which symbols to include at the topmost scope.  * includes everything."
				}
			}
		}
	},
	"scripts": {
		"vscode:prepublish": "tsc -p ./",
		"compile": "tsc -watch -p ./",
		"postinstall": "node ./node_modules/vscode/bin/install",
		"test": "node ./node_modules/vscode/bin/test"
	},
	"devDependencies": {
		"typescript": "^2.0.3",
		"vscode": "^1.1.0",
		"mocha": "^2.3.3",
		"@types/node": "^6.0.40",
		"@types/mocha": "^2.2.32"
	},
	"__metadata": {
		"id": "d960eabf-f421-4568-8be0-2633af2c37b0",
		"publisherId": "65792330-895e-4895-a673-b152cfd2fcfa",
		"publisherDisplayName": "Patryk Zawadzki"
	}
}

**Comment by leanderr** [comment]
Thanks @davidesnc . I deleted the name property. Don't delete this line or stuff won't work anymore.
"name": "Code Outline"

**Comment by benoitmasson** [comment]
Note that as from [version 1.24](https://code.visualstudio.com/updates/v1_24#_outline-view), code outline is now integrated in VS Code in the “Explorer” section, and is pretty complete.

**Comment by patrys** [comment]
Yes, this extension will be deprecated once 1.25 ships with the complete Outline implementation.
