### ISSUE TITLE
Outline pane vanished from explorer pane

### ISSUE THREAD

**Issue by bardware** [patrys/vscode-code-outline#121]
I updated VSCode to version 1.23.1 an don't see the outline pane below the file explorer any more.
I see a new button and have to switch between file explorer and outline.

![20180511_vscode](https://user-images.githubusercontent.com/802702/39913877-a2a23b1a-5503-11e8-8d81-ef7bbe80e573.PNG)

**Comment by patrys** [comment]
This is working as intended. I got many many requests to give it its own section separate from the explorer.

**Comment by bardware** [comment]
Had no idea. Thank you!

**Comment by mzvast** [comment]
It's inconvenient for who need to tack with lots of files.
Switching between pane is not efficient.

**Comment by winzig** [comment]
Any plans to have a setting to let it appear in the explorer view again?

**Comment by patrys** [comment]
There is currently no way to have this optional (there are no APIs to dynamically move viewlets) and I intend to keep it separate from explorer by default.
