### ISSUE TITLE
Support @blocks in CSS/SCSS

### ISSUE THREAD

**Issue by cdCorey** [patrys/vscode-code-outline#128]
I realize CSS/SCSS isn't in the official list of supported languages, but it works, so apparently they are supported in some fashion. However, @blocks (e.g., @media queries in CSS and @include block-level mixins in SCSS) don't show up as part of the node tree. It would be great if they did.

**Comment by patrys** [comment]
That's up to whichever CSS/SCSS plugin you're using. Code Outline does not do any language parsing and relies on the symbol providers shipped with language support plugins.

**Comment by cdCorey** [comment]
There is no plugin, it seems to be built into VS Code. But thanks, that
makes sense.

--
Corey Caswick
Chatman Design
chatmandesign.com <http://www.chatmandesign.com>
