### ISSUE TITLE
Is possible to add support to other language?

### ISSUE THREAD

**Issue by mr-ocean** [patrys/vscode-code-outline#130]
Hi all!
This isn't an Issue but only a question.

This plugin is very good and save me my work times. However, I use many different programming language and not all are supported.
It is possible to add manually the support to other language?

Thanks :)

**Comment by patrys** [comment]
You just need to find (or write) a plugin that provides symbol information for the currently opened file. Take a look at the table in the README file for a list of plugins that are known to work.
