### ISSUE TITLE
Hide imports (Python)

### ISSUE THREAD

**Issue by egabrum** [patrys/vscode-code-outline#136]
(At least in Python) the outline shows everything that is imported in the from
`from xxx import yyy, zzz`
This creates a lot of useless noise in the outline.
Is there a way to not show these imports?

**Comment by patrys** [comment]
Code Outline knows nothing about the programming language so it does not know which lines are imports. It displays all symbols as reported by the language-specific extension (in this case the Python extension maintained by Microsoft). I am planning to include folding regions when they become accessible to extensions so there's a chance of the Python extension either not reporting imports at all or grouping them into a folding region that would eventually group them in the symbol tree.

**Comment by egabrum** [comment]
Too bad. Thanks for looking into this.
