### ISSUE TITLE
Hide imports

### ISSUE THREAD

**Issue by jhertz123** [patrys/vscode-code-outline#139]
In TypeScript (or any language) how do i hide the imports from Code Outline?

**Comment by patrys** [comment]
It is up to language-specific extensions to decide which symbols are reported. There is currently no way for Code Outline to detect that a symbol is an import.

**Comment by jhertz123** [comment]
If anyone else has a similar requirement this is what I did to get what I wanted.

"symbolOutline.topLevel": ["Method", "Class", "Property"]
