### ISSUE TITLE
setting to expand outline to levels

### ISSUE THREAD

**Issue by rsperl** [patrys/vscode-code-outline#15]
This is awesome. The minimap they provided isn't that useful, but this really is. Would you consider adding a setting to allow a default number of levels to be automatically expanded? For instance, if codeoutline.expandLevels: 2, then whenever the outline was loaded or refreshed, two levels of the outline would be expanded, and the rest collapsed.

**Comment by patrys** [comment]
Version 0.0.10 lets you configure which container types should be expanded by default ✨
