### ISSUE TITLE
Error on launch with Insiders 

### ISSUE THREAD

**Issue by smlombardi** [patrys/vscode-code-outline#16]
Using the version of Insiders released 6/19, Version 1.14.0-insider (1.14.0-insider) 2017-06-19T13:39:50.004Z

I got an error dialog at launch and this in the console:

![screen shot 2017-06-19 at 10 50 33 am](https://user-images.githubusercontent.com/835148/27291112-56423fc6-54dd-11e7-8383-f64a1174e601.png)

**Comment by patrys** [comment]
This is fixed now.
