### ISSUE TITLE
Auto-expand the tree?

### ISSUE THREAD

**Issue by Wideshanks** [patrys/vscode-code-outline#21]
Every file I enter will refresh the Code Outline panel but collapse the tree. I have to manually expand it? It is possible to keep it fully expanded all the time?

**Comment by jens1o** [comment]
Would love to have this, too. 

In php oop development, this is especially useful.
![image](https://user-images.githubusercontent.com/11234139/27675276-99f2c0d2-5ca9-11e7-8c8f-47e17db08b31.png)

**Comment by patrys** [comment]
This should work much better in 0.0.10 ✨
