### ISSUE TITLE
Incorrect order of items

### ISSUE THREAD

**Issue by Danieleeee** [patrys/vscode-code-outline#23]
Hi,
can we have the same order in Symbols list?
![1](https://user-images.githubusercontent.com/22749175/27678357-3f0c4614-5cb5-11e7-99d0-81f799747cf8.png)

The current sorting does not reflect the structure of package. PACKAGE variable must stay on the top.
The icons are also different.
Thanks

**Comment by patrys** [comment]
Currently the sorting is grouped by symbol type and then sorted alphabetically. I can think about adding a toggle for this one day if it's useful.

**Comment by Danieleeee** [comment]
Can you put the symbol type for **_package_** in the top?

**Comment by Danieleeee** [comment]
Iven vscode.SymbolKind.Struct icon is different:
![1](https://user-images.githubusercontent.com/22749175/27685013-b5392f52-5ccc-11e7-95d1-57137161bed4.png)

**Comment by radix** [comment]
I would prefer to see the tree in order that the symbols appear in the source code.

**Comment by KPhoenix** [comment]
I would also love to see a toggle that leaves the symbols in their initial order rather than sorting alphabetically. It's useful when dealing with prose, too, as it makes more sense to see a document's sections/headings in the same order as the text itself. Thanks for the great extension—been waiting for something like this to hit VSCode ever since I first tried it out.

**Comment by matmel** [comment]
In other IDE, I typically use the code outline to navigate in long source code files and use it as a table of contents. So +1 for the toggle to switch between sorted symbols and symbols in the order they appear.

**Comment by ppggff** [comment]
临时方案，注释掉

**Comment by ppggff** [comment]
Temporary workaround: comment out or delete `tree.sort();` in `symbolOutline.js` line 101.

**Comment by patrys** [comment]
I believe this is fixed as of 0.0.8 where you can disable sorting entirely or provide a custom sorting order (#28).
