### ISSUE TITLE
Variables local to closures are showing as top-level vars in outline

### ISSUE THREAD

**Issue by faintsignal** [patrys/vscode-code-outline#30]
As of version 0.0.8 JavaScript variables that are defined locally in closures are appearing as "top-level" variables in the code outline, rather than as variables of anonymous functions within their respective contexts.

Example below is the outline of a file defining an ES6 "class", the editor showing a method in which the highlighted variable in the outline is a variable defined locally within a closure within the method.  Each of the "blue" variables in the outline are similarly defined within closures within some method.  (Configuration setting **symbolOutline.topLevel** is set to `["*"]`.)

![2017-07-19 16_54_14-lot js models visual studio code](https://user-images.githubusercontent.com/29309408/28389357-c45958fe-6ca3-11e7-856b-5385ae73706b.png)

**Comment by faintsignal** [comment]
I may have jumped the gun here -- looks like I need to check the configuration for the plugin.

**Comment by patrys** [comment]
This is currently true. I have an idea on how to improve this for languages that report proper symbol ranges though.
