### ISSUE TITLE
[Enhancement] Outline on right side of the editor

### ISSUE THREAD

**Issue by mskocik** [patrys/vscode-code-outline#32]
It would be great to have option to switch to the right side of editor area - where minimap is currently present.
![image](https://user-images.githubusercontent.com/25513620/28527788-f1a19736-708b-11e7-848d-98ee42f5df42.png)

**Comment by patrys** [comment]
It would be but currently VSCode does not offer any integration points other than the explorer tab 😢

**Comment by Frodox** [comment]
Maybe we can open Feature request in vsc to add such points (like instead of minimap, or create second explorer tab on right) ?
