### ISSUE TITLE
[BUG] Outline does not work as intended

### ISSUE THREAD

**Issue by peterschussheim** [patrys/vscode-code-outline#33]
## VSCode Version:
- VSCode Version: Code - Insiders 1.15.0-insider (fed03b66ac8acdac93897727a1d19ee0f6898bf2, 2017-07-25T07:20:25.274Z)
- OS Version: Darwin x64 16.7.0

## Description
I've used this extension since it was released and never had problems until today.  The problem is not consistent; **sometimes an outline will show, sometimes not.  When an outline is shown, it fails to update (tried refreshing using button).**

Please let me know what info would be helpful for you to debug.

**Comment by patrys** [comment]
Are there any errors indicated in VSCode's developer console? Do you use custom values for any of the settings?

**Comment by peterschussheim** [comment]
Closing this issue as the problem has gone away.  Thanks!
