### ISSUE TITLE
Non-Alphabetic Sort Order 

### ISSUE THREAD

**Issue by briancleland** [patrys/vscode-code-outline#36]
Hi, I'm using this extension to get an overview of markdown files that I'm working on. Headers are currently sorted in alphabetic order. Would it be possible to get an option for headers to appear in the order that they occur in the text, rather than in alphabetic order?

**Comment by fenying** [comment]
According to README.md, you can use the option `symbolOutline.doSort` and set it to `false`.

https://github.com/patrys/vscode-code-outline#extension-settings

**Comment by briancleland** [comment]
Turns out I had mistyped an option. Working now. Thanks.
