### ISSUE TITLE
Code outline doesn't linked with editor

### ISSUE THREAD

**Issue by danil-tolkachev** [patrys/vscode-code-outline#38]
## Steps to reproduce:
- Open file in right editor panel
- Click to outline symbol item

## Actual behavior
- File open in the left editor panel in preview mode

## Desired behavior
- Navigate to symbol in right panel

## Environment data
VSCode version: 1.15.0
Code Outline version: 0.8.0

**Comment by patrys** [comment]
This was fixed in 0.0.9 🎊
