### ISSUE TITLE
Different icon from Function and Procedure

### ISSUE THREAD

**Issue by Danieleeee** [patrys/vscode-code-outline#4]
I'have installed v.003, very good job!

Is possible to have different icons from Function and Procedure?
![schermata 2017-06-12 alle 22 23 29](https://user-images.githubusercontent.com/22749175/27053564-07d1a468-4fbe-11e7-8869-92e6c5aed64f.png)

**Comment by patrys** [comment]
Could you show the symbol list for the same file? I'd like the icons to match those used by VSCode.

**Comment by Danieleeee** [comment]
For procedure and function the icons are the same:
![1](https://user-images.githubusercontent.com/22749175/27070643-2cf16baa-501a-11e7-92ac-91cfb6eb313c.png)
I notice that you change the package icon (that is good), so I thought you could also improve the function/procedure icons.

**Comment by patrys** [comment]
Would you mind opening a vscode issue for this? I think it would be better to aim for consistency and improve the underlying platform instead.

**Comment by Danieleeee** [comment]
Open:
[issues 28592](https://github.com/Microsoft/vscode/issues/28592)
