### ISSUE TITLE
Focus issues when in split screen mode

### ISSUE THREAD

**Issue by PrinsEdje80** [patrys/vscode-code-outline#41]
VSCode 1.15.1
Code Outline 0.0.8

When having a file opened in a split editor modus (split only once via ctrl+\, haven't tested for more splits), but I have either the file open only in the bottom one (1) OR the open in both windows, but the focus on the bottom one (2), selecting any of the items in the list of Code Outline gives the following unwanted result.
For scenario 1: opens a "quick view" window in the top split editor and focuses on the requested item. I expect it to focus on the bottom editor and focus on the requested item.
For scenario 2: focuses on the top split editor and focuses on the requested item. Again, I expect it to focus on the bottom editor and focus on the requested item.

**Comment by patrys** [comment]
This is a legitimate bug but I'm not sure yet how to programmatically focus an editor instance.

**Comment by danil-tolkachev** [comment]
possibly related to #38

**Comment by patrys** [comment]
You're right, this is a duplicate. I'll close this in favor of #38.
