### ISSUE TITLE
Boost FOREACH confused the outline tree

### ISSUE THREAD

**Issue by kokolorix** [patrys/vscode-code-outline#43]
If a Method contains a boost foreach macro, the method doesnt appaer in the outline tree.
Look the [screenshot](https://1drv.ms/i/s!AnFNp4steYRgiedQ2qnrpBikGQQkIQ) for more clarity

**Comment by patrys** [comment]
Could you please provide the smallest possible file that reproduces this? Also please share a list of vscode plugins I need to install if any.

**Comment by gludion** [comment]
Hello, I've a similar issue in typescript:
```
class ForeachBug {
	method1() {
		let a = 1;
		let b = 2;
	}
	method2() {
		let p = [2,3,4];
		p.forEach(element => {
			let u = 1;
		});
	}
}
```
the variable u inside the forEach block is put on top of outline hierarchy.

**Comment by patrys** [comment]
I use the symbol provider and in this case I think I have a clean solution. The only problem is finding time to implement it 😄 

My idea is to to use the reported ranges of symbols to deduce which symbols are contained by which. The code currently depends on scope names which unfortunately means that anonymous functions break it.

**Comment by faintsignal** [comment]
@gludion In your case it looks like the same problem I have ( issue #30 ).

**Comment by fenying** [comment]
There could be a temporary solution: use the option `symbolOutline.topLevel` to hide variables, if you don't need to show the variables.

```json
    "symbolOutline.topLevel": [
        "Module",
        "Class",
        "Interface",
        "Namespace",
        "Object",
        "Package",
        "Struct",
        "Function",
        "Method",
        "Property"
    ]
```

**Comment by gludion** [comment]
it works, but then variables a and b in method1() (in my example above) are now hidden (even though they were correctly reported as children of method1()).

**Comment by fenying** [comment]
@gludion Yes, that's why I said it's a TEMPORARY SOLUTION.
