### ISSUE TITLE
Feature request: YAML support

### ISSUE THREAD

**Issue by ffxsam** [patrys/vscode-code-outline#45]
This is great extension! It would be even better if it supported YAML files 😉

**Comment by fbricon** [comment]
If the yaml extension provided support for `textDocument/documentSymbol`, then vscode-code-outline would just work.

cc @JPinkney, @gorkem

**Comment by fbricon** [comment]
It actually works with https://github.com/redhat-developer/vscode-yaml

<img width="1032" alt="screen shot 2017-11-20 at 10 26 05 am" src="https://user-images.githubusercontent.com/148698/33025973-5d4402b8-cddd-11e7-8422-7bff7f9dd30d.png">

**Comment by ffxsam** [comment]
Ahh yes. I installed the extension:
https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

But unfortunately it just puts red lines all over my AWS CloudFormation template because it doesn't like the special syntax.

![image](https://user-images.githubusercontent.com/12532733/33026149-697569d0-cdd5-11e7-847c-f90a52317cc1.png)

**Comment by ffxsam** [comment]
Will do! Thanks.
