### ISSUE TITLE
Is it possible to hide function members?

### ISSUE THREAD

**Issue by scorredoira** [patrys/vscode-code-outline#46]
The outline shows function short lived variables which is too detailed in my opinion:

![image](https://user-images.githubusercontent.com/1644405/31044496-9756987e-a5d0-11e7-8e4a-0e86d44d4ed9.png)

Is it possible to hide them? Also I have tried to put them at the end but sorting doesn't seem to work for me. I used:

```
    "symbolOutline.sortOrder": [
        "Module",
        "Function",
        "Interface",
        "Class",
        "Constant",
        "Method"
    ],

```

Thank you for this, it was the only thing that I missed in VSCode

**Comment by patrys** [comment]
Can you see if this is still an issue in 0.0.11?

**Comment by scorredoira** [comment]
It's solved, thank you!
