### ISSUE TITLE
Add CSS support

### ISSUE THREAD

**Issue by stanislavgeorgiev** [patrys/vscode-code-outline#49]
It would be great to have support for CSS outline. The default Ctrl+O does provide a list of classes.

Stretch goal: provider a tree like structure of the classes

**Comment by patrys** [comment]
You should be able to see all symbols that are displayed by Ctrl+O as this extension uses the same symbol provider API.

**Comment by patrys** [comment]
I'm testing this locally and it seems to work as expected with CSS files. This plugin does not do anything language-specific and only relies on the symbol providers included with various language plugins.

**Comment by stanislavgeorgiev** [comment]
That's really strange. It started working fine now. It could be because I updated my VSCode to 1.17 just now, I don't know.
