### ISSUE TITLE
Reveal symbols in center

### ISSUE THREAD

**Issue by tipleagame** [patrys/vscode-code-outline#52]
When Code Outline reveals a symbol in the editor, `TextEditorRevealType.Default` is used. However, despite its name, it is actually not in agreement with the way the Symbol Outline (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>O</kbd>) works. Also the current behavior provides an inconsistent and disorienting experience, since going down to find the symbol puts the cursor at bottom of the editor, and going up puts it at the top.

It would be more natural to use `TextEditorRevealType.InCenter`. This would make it consistent with the Symbol Outline and consistent as an experience, since the cursor would jump to the center of the editor every time.

**Comment by patrys** [comment]
It used to be `InCenter` but that was super awkward for symbols (like classes) that are longer than the screen. Pressing up and down behaves that way because by default the code is also selected. You can disable that in settings.
