### ISSUE TITLE
Show outline for only methods?

### ISSUE THREAD

**Issue by JerryGoyal** [patrys/vscode-code-outline#54]
Is there any way to show outline for only methods/functions. Right now it's showing variables + methods+packages etc which consumes much of my right bar space.

**Comment by skyfortress** [comment]
`    
"symbolOutline.topLevel": [
        "Function",
        "Method"
      ]
`
Try to use this config. It works for me.

**Comment by JerryGoyal** [comment]
Kudos to @skyfortress answer. issue can be closed now.
