### ISSUE TITLE
JS prototype properties

### ISSUE THREAD

**Issue by ray007** [patrys/vscode-code-outline#59]
would be really nice if they were treated like methods in classes and showed up in the hierarchy below the function they are added on.

**Comment by patrys** [comment]
This extension does not do any extraction on its own, all symbols are provided by the language support extensions (in this case the JS/TS extension).

**Comment by ray007** [comment]
The only extension I've installed in Visual Studio Code is this one.
Could you please point me in the right direction where to ask for this?

**Comment by patrys** [comment]
The JS and TS extensions are part of Code and come with the editor: https://github.com/Microsoft/vscode/tree/master/extensions/javascript
