### ISSUE TITLE
How to hide field in a structure？

### ISSUE THREAD

**Issue by t19903** [patrys/vscode-code-outline#60]
Code outline shows the structure and the fields in it as same level. Is there any way to make it different level or just hide it?

![screen shot 2017-11-10 at 12 00 42 pm](https://user-images.githubusercontent.com/8612862/32642390-0416f09a-c60f-11e7-8f7e-d5e7e0f35910.png)

**Comment by patrys** [comment]
It seems the language plugin for C does not report full symbol ranges for containers. There is little I can do in my plugin but we can open an issue with the C language support plugin if you can tell me which one is in use.

**Comment by patrys** [comment]
I'm going to close this one, please open a bug against the C/C++ extension that you use as Code Outline depends on full symbol ranges being reported.
