### ISSUE TITLE
Eager calls to textDocument/documentSymbol

### ISSUE THREAD

**Issue by fbricon** [patrys/vscode-code-outline#64]
When opening a java file (with vscode-java installed and `"java.trace.server": "messages"`), I see 2 calls to `textDocument/documentSymbol`. Any reason for that? 
I can even see those 2 calls when the code outline view is collapsed. There are no `textDocument/documentSymbol` calls if the vscode-code-outline extension is disabled.

**Comment by patrys** [comment]
That may be a bug, I'll investigate. It should not ask for data unless it's actually needed.

**Comment by patrys** [comment]
I'm unable to reproduce this. I've added `console.trace` next to my call to `vscode.executeDocumentSymbolProvider`. It does not seem to be called more than once per document. I will need some more guidance to get to the bottom of this.
