### ISSUE TITLE
collapse sections on click

### ISSUE THREAD

**Issue by BryanDiLaura** [patrys/vscode-code-outline#68]
I'm not sure if this is a bug, a feature request, or me not setting up my config properly, but for my C++ codebase everything shows up on the top level with no nesting. It would be nice if the tree view would be able to collapse things that are contained in one another, i.e. methods in a class, etc.

Here is a simple example:
``` 
#include <iostream>

#define FUNTIMES 10

using namespace std;
class TestClass{
    public:
        void method1(void){
            cout << "hello from method1" << endl;
        }
        void method2(void){
            cout << "hello from method2" << endl;
        }
    private:
        void method3(void){
            cout << "hello from method3" << endl;
        }
        int a;
        int b;
};

int main(){
    TestClass t;
    t.method1();
    return 0;
} 
```

If this functionality is already available, I think the default settings should be changed to reflect this functionality.

**Comment by patrys** [comment]
This is most likely due to how the symbol information is returned by your C++ plugin. Code Outline can only infer symbol inheritance if the related language plugin returns them as contained regions.

**Comment by ttiganik** [comment]
I have the same problem with my Unity project. I use the Microsoft's C# extension.

[https://imgur.com/a/Dfj8G](url)

`"symbolOutline.topLevel": [
          "Class",
          "Function",
          "Method",
          "Field"
        ],
        "symbolOutline.expandNodes": [
          "Class"
        ]`

If I dont use "Method" in topLevel, it is not shown at all. Its the same with default settings.

**Comment by patrys** [comment]
Please open an issue against the C++ extension and against the C# extension as Code Outline depends on how they are reporting symbols.
