### ISSUE TITLE
Do not select code

### ISSUE THREAD

**Issue by ChrisMiami** [patrys/vscode-code-outline#69]
This is change request, not a bug per se.

When I use the plugin to navigate to a function, the entire function is selected.  This is risky and not necessary, mostly a hassle.  I'm hoping instead that you can put the cursor either at the front of the fn definition or at the end of that same line (which is typically after the opening brace).

**Comment by wanderer06** [comment]
Add `"symbolOutline.doSelect": false` to your settings.

**Comment by patrys** [comment]
I will consider making this the default as indeed selecting the code is sometimes unnecessary.
