### ISSUE TITLE
Move the view to specific sidebar

### ISSUE THREAD

**Issue by David-GH** [patrys/vscode-code-outline#70]
To keep explorer more readable, I think it will be good if we can move the "Code Outline" list to a specific sidebar. The button will be on the activity bar (under Explorer, Git, Search, Extensions).

Perhaps with a badge (like git) to indicate number of functions available...

>Example:
>When I click on Explorer, I see explorer in sidebar
>When I click on Search, I see search options sidebar
>With my proposal, when I click on his icon, Code Outline take place in the sidebar

What do you think ?

Thx.

**Comment by patrys** [comment]
I'd love to do that but as far as I know VS Code does not support custom sidebar panels.

**Comment by David-GH** [comment]
Yes, I understood that after more searches...
It will be great if they allow us to add or remove buttons in the ativity bar with their custom sidebar.

May be later...

**Comment by Frodox** [comment]
same as #32

**Comment by David-GH** [comment]
@Frodox isn't same as #32 

My issue talk about the **possibility to add button on activity bar** (which is on the left side) **and add a custom sidebar view attach to it**.

If we can doing this, we can move lot of things currently in explorer sidebar to their own sidebar (like projects, outline, ...).

I ask this feature because I think the explorer sidebar contain too much elements :smiley:

**Comment by zblove0** [comment]
@David-GH agree!

**Comment by David-GH** [comment]
Someone can attach (or move) this issue to the visual code project ? 
Because the problem isn't with the code outline plugin but with vs code which not permit developers to do what we want...

**Comment by cyangOL** [comment]
https://github.com/Microsoft/vscode/issues/15190
https://github.com/octref/explorer-api-example
[https://github.com/octref/explorer-api-example/blob/master/assets/deps.png](Sample)

**Comment by patrys** [comment]
@cyangOL These features never made it to the stable API.

**Comment by marcio0** [comment]
Is it possible to have the previous behavior through some configuration?

**Comment by patrys** [comment]
Sorry, that's not currently possible as views are not registered programmatically.
