### ISSUE TITLE
[Feature request] Highlight symbol at cursor

### ISSUE THREAD

**Issue by LeThiHyVong** [patrys/vscode-code-outline#71]
Hi, 

It would be great if:
1. The function/method that contain the current cursor will be highlighted. 
2. In additional, all items that are matched or contain matches by Ctrl+F will be highlighted.

Currently, C/C++ navigation is not working on big files. I'm completely lost if my search result fall somewhere middle of super long function. 
I'm not sure where you take the function list from. After experimenting a little bit, seem like your extension get it from C/C++ intellisense (either [CppTools](https://github.com/Microsoft/vscode-cpptools) extension or [GNU global tags](https://github.com/austin-----/code-gnu-global)). 

Thanks.

**Comment by tidyjiang8** [comment]
It will be a great feature I need too :+1:

**Comment by patrys** [comment]
This extension uses the SymbolProvider API to ask the language extension for a list of symbols defined in the currently open document.

As for highlighting the currently active symbol, this is not currently supported by VS Code, see #12.
