### ISSUE TITLE
Place function definition on 1/3 from screen top

### ISSUE THREAD

**Issue by Frodox** [patrys/vscode-code-outline#73]
First of all, I use
`"symbolOutline.doSelect": false`, because code selecting is useless for me.

And in this case when I click function name, currently it can be two cases:
1) if function name is below screen
then I go to the definition which in the bottom of the screen, which is a bit useless. So I need to manually scroll up ...
![screenshot_2017-12-10_23-46-33](https://user-images.githubusercontent.com/3653069/33809223-8b8a7c60-de04-11e7-9f4b-6e82f874c119.png)

2) if function definition is above screen
then I go to the definition which is top of the screen, which is better, but I do not see any previous code
![screenshot_2017-12-11_00-13-01](https://user-images.githubusercontent.com/3653069/33809447-1babf1d6-de08-11e7-8e2c-64c7059df89b.png)

Both looks like a bit logic bug.
Also vsc's 'go to symbol' (`@func_name`, ctrl+shift+o) places function definition in the middle of screen. 

It would be very cool if func definition appears somewhere like 1/3 from top of screen (like in Geany), so I can see some code before and start reading or choose another function quickly. Or it can be configurable.

**Comment by patrys** [comment]
There's curently a bug in how it behaves if selecting code is disabled. The revealing however is handled by VS Code.

**Comment by patrys** [comment]
#80 is similar to this one, your original issue (code not being visible) should be fixed however so I'm going to close this one.
