### ISSUE TITLE
empty list

### ISSUE THREAD

**Issue by tboulogne** [patrys/vscode-code-outline#76]
Hello, 

home page detailled :

> Depending on other extensions you have installed the symbol list may initially return an empty list. Use the "Refresh" button next to the title to fix this.

I disable ALL my extensions, and i continue to get empties list :-( after refreshing.

A définitive way to solde this please ?

Thanks for help.

Regards

**Comment by chris-smearing** [comment]
Same here. VS Code version 1.19.1 (x64) using a PHP file. No other extensions are enabled.

**Comment by tboulogne** [comment]
Hello

I installed extension PHP intelissens and it work. Don't ask me why !

**Comment by tmdevde** [comment]
this did the trick for me too.
