### ISSUE TITLE
Python Support

### ISSUE THREAD

**Issue by timharris777** [patrys/vscode-code-outline#78]
Can python support be added? Thanks!

**Comment by patrys** [comment]
I use it with Python all the time. Please install and enable the [official Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) by Microsoft.

**Comment by timharris777** [comment]
I have had the extension installed. I looked into it further and it seems to be an issue with vscode pulling symbols for python. I installed ctags but it will not pull the symbols even when I press cmd+shift+o. I opened an issue in the vscode-python repository.
