### ISSUE TITLE
outline for custom file extensions - php

### ISSUE THREAD

**Issue by halmsx** [patrys/vscode-code-outline#81]
hi

so i have custom extensions for php files like .module and .info. how do i enable outline for them? thanks in advance.

**Comment by barryrld** [comment]
@halmsx 
I had an issue with PHP extensions not working at all - not even for *.php.

It looks like you may be using Drupal looking at the .module and .info extensions.

I installed the [PHP Intellisense](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense) and [PHP Symbols](https://marketplace.visualstudio.com/items?itemName=linyang95.php-symbols) extensions along with the following User Settings (`Ctrl`+`,`) and I now see outlines in all Drupal based extensions.


```
{
    ...
        "files.associations": {
            "*.inc": "php",
            "*.theme": "php",
            "*.module": "php",
            "*.info": "php"
        }
    ...
},
```

I hope this helps.
