### ISSUE TITLE
Feature Request: Order alphabetically within class/module/constant etc.

### ISSUE THREAD

**Issue by gmonkman** [patrys/vscode-code-outline#82]
Great add in.

Could an option be added to sortOrder to order alphabetically rather than by line number within the objects defined under:
  "symbolOutline.sortOrder": [
    "Class",
    "Module",
    "Constant",
    "Interface",
    "*",
    "Constructor",
    "Function",
    "Method"
  ]

**Comment by patrys** [comment]
Closing as this is already possible.
