### ISSUE TITLE
Feature Request: perl language support

### ISSUE THREAD

**Issue by mainjoehere** [patrys/vscode-code-outline#86]
Hello,

it would be nice to have support for the perl language.

**Comment by Simerax** [comment]
Hey mainjoehere,

this already works.
Get the "Perl" Extension from Henrik Sjööh and you are ready to go.

**Comment by patrys** [comment]
Hey, would you mind submitting a pull request to update the README? It now holds a list of extensions to install for various languages.

**Comment by patrys** [comment]
That's why I'm asking for someone to add it there 😄
