### ISSUE TITLE
[Feature Request][Possible Bug]

### ISSUE THREAD

**Issue by thejtshow** [patrys/vscode-code-outline#89]
Hello,

two things:
1. Highlighting when selecting a method code outline (in a Python file) doesn't highlight the last character
2. Can we turn highlighting into an optional feature? I would prefer clicking on a method to place the cursor at the beginning of the instance instead of highlighting the whole thing. Minor preference, but it would be awesome to have some user controls such as this :)

**Comment by thejtshow** [comment]
Duh. Helps if I read docs. Issue 2 seems to be a thing already, but issue 1 still exists.

**Comment by patrys** [comment]
Number 1 is likely a bug in the VS Code Python plugin (I think I might have introduced it personally but it should be tracked there).

For number 2 I have a plan. As individual items can now have actions I want to have single click move the cursor and a dedicated action select the entire definition.

**Comment by thejtshow** [comment]
Thanks for the quick turnaround response. What I was looking for was essentially the `symbolOutline.doSelect` option, which I found directly after posting, per usual. Though I will say that differentiating between selecting a location and opening the tree view should be separate actions, or, say, a single select opens the dropdown, but sets it to a state where it will auto close when deselected. Double clicking could leave it open permanently. But, as I understand it, the API you are working with is quite limited

**Comment by patrys** [comment]
I agree but there's no control over tree behavior currently. It's just how VS Code works for now.

**Comment by thejtshow** [comment]
Hopefully that changes soon :D Thanks for developing a great extension.

**Comment by patrys** [comment]
I'm going to close this as the original problems are no longer an issue with 0.1.0. Other features are already tracked by separate issues.
