### ISSUE TITLE
The function list in "CODE OUTLINE" window is not correct when using macro.

### ISSUE THREAD

**Issue by boram1288** [patrys/vscode-code-outline#95]
`
#include <string.h>

#define FOREACH(i) for((i) = 0; (i) < 10; (i)++)

int main(void)
{
	int n = 0;

	FOREACH(n) {
		printf("Hello %d\n", n);
	}

	return 0;
}
`

When using macro like above, the function list in "CODE OUTLINE" window is not correct.
I expect to see the "main" in "CODE OUTLINE" window. But the window shows "FOREACH" only.

**Comment by patrys** [comment]
I suspect that it's what the C/C++ plugin reports. Does the same problem exist when using the "go to symbol" feature in VS Code?
