### ISSUE TITLE
Showing every function twice

### ISSUE THREAD

**Issue by safa-sharpmind** [patrys/vscode-code-outline#96]
I have installed code outline along with the php symbols extention for php code. when I expand the code outline in explorer every functions are displayed twice. How can i overcome this issue ?

![image](https://user-images.githubusercontent.com/14110981/37562496-c3b27f34-2a8f-11e8-87de-bfea6a0545b0.png)

**Comment by patrys** [comment]
Does the same problem exist when using "go to symbol" in VS Code?

**Comment by safa-sharpmind** [comment]
Hi,

This was happening due to the vscode simple-ftp plugin, i just uninstalled it and then it was back to normal 

![image](https://user-images.githubusercontent.com/14110981/37578609-08e873c6-2b60-11e8-8400-5960f670c734.png)

Thanks for this great plugin :+1:

**Comment by safa-sharpmind** [comment]
Yes even on 'go to symbol' it shows the same 

![image](https://user-images.githubusercontent.com/14110981/37578874-5ea16100-2b61-11e8-8244-670d04db192f.png)

when i click the first function the cursor moves to to the end of the name and the second one cursor moves to the end of the '()'brackets. 

Any way to overcome this ?

**Comment by patrys** [comment]
In that case I suggest that you open an issue for whatever PHP plugin you use. Code Outline relies on the symbol data provided by the plugin and as demonstrated by the "go to symbol" dialog the plugin reports each name twice.
